config-version: 2
name: 'fivetran_log'
version: '1.0.0'
require-dbt-version: [">=1.3.0", "<2.0.0"]

models:
  fivetran_log:
    +materialized: table
    +schema: fivetran
    staging:
      +schema: stg_fivetran
      tmp:
        +materialized: view

vars:
  fivetran_log:
    account: "{{ source('fivetran', 'account') }}"
    account_membership: "{{ source('fivetran', 'account_membership') }}"
    incremental_mar: "{{ source('fivetran', 'incremental_mar') }}"
    connector: "{{ source('fivetran', 'connector') }}"
    credits_used: "{{ source('fivetran', 'credits_used') }}"
    destination: "{{ source('fivetran', 'destination') }}"
    destination_membership: "{{ source('fivetran', 'destination_membership') }}"
    log: "{{ source('fivetran', 'log') }}"
    transformation: "{{ source('fivetran', 'transformation') }}"
    trigger_table: "{{ source('fivetran', 'trigger_table') }}"
    user: "{{ source('fivetran', 'user') }}"
    usage_cost: "{{ source('fivetran', 'usage_cost') }}"
