database_key: fivetran_platform_database
schema_key: fivetran_platform_schema

dbt_versions: ">=1.3.0" "<2.0.0"

table_variables:
  fivetran_platform_using_destination_membership:
    - destination_membership
  fivetran_platform_using_user:
    - user

destination_configurations:
  databricks:
    dispatch:
      - macro_namespace: dbt_utils
        search_order: [ 'spark_utils', 'dbt_utils' ]